print('after push to github')
print('added branch called branch_lambda_1')
print('added branch_1')
print('added line 21, because could not commit')
print('on file without __main__ code add this print statement')
print('created branch_T_1')
print('in branch_T_2')
print('added branch_T_3')
